import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';

const base=process.env.BAROS_AUDIT_URL||'http://127.0.0.1:8137';
const dom=new JSDOM('<div id="app"></div><div id="modal-root"></div><div id="toast-root"></div>',{url:base+'/app',pretendToBeVisual:true});
for(const key of ['window','document','location','history','localStorage','FormData','Event','MouseEvent','HTMLElement'])globalThis[key]=dom.window[key];
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});
globalThis.confirm=()=>true;
dom.window.scrollTo=()=>{};
dom.window.HTMLElement.prototype.scrollIntoView=function(){};
const nativeFetch=globalThis.fetch;
const requests=[];
globalThis.fetch=async(path,options={})=>{
 const url=new URL(path,base).href,headers=new Headers(options.headers||{});
 const cookie=dom.cookieJar.getCookieStringSync(base);
 if(cookie)headers.set('cookie',cookie);
 const response=await nativeFetch(url,{...options,headers});
 for(const c of response.headers.getSetCookie())dom.cookieJar.setCookieSync(c,base);
 requests.push({path:new URL(url).pathname,method:options.method||'GET',status:response.status});
 return response;
};
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function until(test,message){for(let i=0;i<200;i++){if(test())return;await sleep(20)}throw new Error(message+'; '+document.body.textContent.slice(-800));}
function element(selector){const e=document.querySelector(selector);assert(e,'Missing '+selector);return e;}
function click(selector){element(selector).click();}
function input(selector,value){const e=element(selector);e.value=value;e.dispatchEvent(new Event('input',{bubbles:true}));}
function submit(selector){element(selector).dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));}
async function request(path,method='GET',body){const r=await fetch('/api'+path,{method,headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json();assert(r.ok,JSON.stringify(data));return data;}
await request('/auth/setup','POST',{token:'baros-ui-audit-only',name:'Тестовый владелец',login:'ui.owner',password:'audit-owner-password'});
await import('./ui/app.js');
const core=await import('./ui/core.js?v=2.4.1');
await until(()=>document.querySelector('[data-new-venue]'),'Owner screen');
click('[data-new-venue]');
assert(document.querySelector('#venue-form'),'Owner button must retain its handler after shell mounting');
input('#venue-form [name=name]','UI аудит заведения');
submit('#venue-form');
await until(()=>document.querySelector('[data-enter-venue]'),'Venue create must refresh the mounted page');
const venue=(await core.api('/venues'))[0];
const invitation=await core.api('/venues/'+venue.id+'/invite','POST',{});
click('[data-enter-venue]');
await until(()=>document.querySelector('[data-create]'),'Owner remote dashboard');
click('[data-create]');
input('#new-course [name=title]','Учебный курс UI');
input('#new-course [name=description]','Проверка реальных действий интерфейса');
submit('#new-course');
await until(()=>document.querySelector('[data-add-lesson]'),'Course editor');
const courseId=Number(location.pathname.split('/').at(-1));
click('[data-add-lesson]');
input('#lesson-title','Стандарты подачи');
input('#lesson-body','В нашем заведении лимонад подают в высоком стакане со льдом. Сначала кладут лёд, затем добавляют напиток.');
click('[data-save]');
await until(()=>requests.some(r=>r.path==='/api/courses/'+courseId&&r.method==='PUT'&&r.status===200),'Save theory');
click('[data-editor-tab=questions]');
click('[data-add-question]');
input('#question-form [name=prompt]','В какой посуде подают лимонад по стандарту заведения?');
for(const [i,value] of ['Высокий стакан','Кружка','Бокал для вина','Рюмка'].entries())input('#question-form [name=choice'+i+']',value);
input('#question-form [name=explanation]','В теории указан высокий стакан со льдом.');
submit('#question-form');
await until(()=>!document.querySelector('#question-form'),'Save question in editor');
click('[data-editor-tab=settings]');
input('#course-settings [name=quiz_size]','1');
submit('#course-settings');
await until(()=>document.querySelector('[data-publish]')&&!core.state.dirty,'Save settings');
click('[data-publish]');
element('#publish-form [name=reviewed]').checked=true;
submit('#publish-form');
await until(()=>!document.querySelector('#publish-form'),'Publish course');
assert.equal((await core.api('/courses/'+courseId)).published,true);
console.log('OWNER: create venue, remote access, create course, edit theory/question/settings, publish OK');
// A direct game link asks an unscoped owner to choose a venue and retains the destination.
core.setOrg('');
const beforeVenueSelection=requests.length;
core.go('/app/games/'+courseId);
await until(()=>document.querySelector('[data-enter-venue]')&&document.body.textContent.includes('Выберите заведение'),'Owner game venue picker');
assert(!requests.slice(beforeVenueSelection).some(r=>r.path==='/api/learning'),'Owner must not fall through to employee API');
click('[data-enter-venue]');
await until(()=>document.querySelector('.game-mode-grid'),'Return to requested game board');
assert.equal(location.pathname,'/app/games/'+courseId);
assert(document.body.textContent.includes('Предпросмотр'));
console.log('OWNER: direct game link, venue selection, preserved destination and preview OK');

core.go('/app/settings');
await until(()=>document.querySelector('#profile-form'),'Owner profile');
input('#profile-form [name=name]','Владелец после UI сохранения');
submit('#profile-form');
await until(()=>core.state.me.account.name==='Владелец после UI сохранения','Profile persisted');
click('[data-logout]');
await until(()=>document.querySelector('#auth-form')&&location.pathname==='/','Owner logout');
assert.equal(localStorage.getItem('baros:venue'),null);
assert.equal((await fetch('/api/me')).status,401);
core.go('/join');
await until(()=>document.querySelector('[name=code]'),'Employee join');
for(const [name,value] of Object.entries({code:venue.join_code,name:'UI сотрудник',login:'ui.employee',password:'audit-employee-password'}))input('#auth-form [name='+name+']',value);
element('#auth-form [name=positions][value=bartender]').checked=true;
submit('#auth-form');
await until(()=>core.state.me?.account?.role==='employee'&&document.querySelector('a[href="/app/learn/'+courseId+'"]'),'Employee assigned published course');
core.go('/app/learn/'+courseId);
await until(()=>document.querySelector('[data-complete-lesson]'),'Employee theory');
await sleep(10600);
click('[data-complete-lesson]');
await until(()=>document.querySelector('[data-start-exam]')&&!element('[data-start-exam]').disabled,'Complete actual theory reading');
click('[data-start-exam]');
await until(()=>document.querySelector('[name=answer]'),'Exam screen');
const answer=element('[name=answer]');answer.checked=true;answer.dispatchEvent(new Event('change',{bubbles:true}));
await until(()=>document.querySelector('#answer-state')?.textContent==='Ответ сохранён','Answer persisted');
click('[data-finish-exam]');
await until(()=>document.querySelector('.result-hero'),'Exam finished and result rendered');
const learner=await core.api('/learning');assert.equal(learner.attempts,1);assert.equal(learner.completed,1);
core.go('/app/history');
await until(()=>document.querySelector('#page-content')?.textContent.includes('Учебный курс UI'),'Employee history');
console.log('EMPLOYEE: self registration, assignment, theory, randomized exam, answer save, result and history OK');
core.go('/app/cards');await until(()=>document.querySelector('a[href="/app/cards/'+courseId+'"]'),'Employee flashcards catalogue');
core.go('/app/cards/'+courseId);await until(()=>document.querySelector('[data-flip]'),'Published flashcard deck');
assert.equal(element('[data-flip]').getAttribute('aria-pressed'),'false');const originalFace=element('[data-flip]');click('[data-flip]');
assert.equal(element('[data-flip]'),originalFace,'Flip keeps the same DOM for the CSS animation');assert.equal(element('[data-flip]').getAttribute('aria-pressed'),'true');
assert.equal(element('.flashcard-answer').textContent,'Высокий стакан');click('[data-remember=yes]');
await until(()=>/1 \/ 1/.test(element('.practice-progress').textContent),'Card mark persisted');assert.equal((await core.api('/learning')).attempts,1);
const {mountDeck}=await import('./ui/cards.js?v=2.4.1');const fixture=document.createElement('section');document.body.append(fixture);
mountDeck(fixture,{revision_id:'gesture-test',cards:[{id:0,question:'First?',answer:'First answer'},{id:1,question:'Second?',answer:'Second answer'}]});
function pointer(target,type,x,y){target.dispatchEvent(new MouseEvent(type,{bubbles:true,clientX:x,clientY:y,button:0}))}
let gesture=fixture.querySelector('[data-flip]');pointer(gesture,'pointerdown',250,100);pointer(gesture,'pointerup',80,108);
await until(()=>fixture.querySelector('.flashcard-question')?.textContent==='Second?','Swipe left advances');
gesture=fixture.querySelector('[data-flip]');gesture.click();assert.equal(gesture.getAttribute('aria-pressed'),'true');
pointer(gesture,'pointerdown',70,100);pointer(gesture,'pointerup',240,106);await until(()=>fixture.querySelector('.flashcard-question')?.textContent==='First?','Swipe right returns');
gesture=fixture.querySelector('[data-flip]');pointer(gesture,'pointerdown',180,70);pointer(gesture,'pointerup',200,250);assert.equal(fixture.querySelector('.flashcard-question').textContent,'First?','Vertical scrolling does not change cards');
gesture.dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));await until(()=>fixture.querySelector('.flashcard-question')?.textContent==='Second?','Keyboard advances');
core.state.cleanup?.();core.state.cleanup=null;fixture.remove();
const {renderLesson}=await import('./ui/learning-ui.js?v=2.4.1');const safe=renderLesson('## Факты\nВ напитке 2.5 мл сиропа. <img src=x onerror=alert(1)>\n\n4. Налейте 20 мл.\n> Важно: **90 °C**');const parsed=new JSDOM(safe).window.document;
assert(!parsed.querySelector('img'),'Lesson renderer escapes source HTML');assert(safe.includes('2.5 мл'));assert.equal(parsed.querySelector('li').value,4);assert(parsed.querySelector('.learning-fact strong'));
console.log('CARDS: published API, flip DOM animation, remembered state, left/right pointer swipes, vertical-scroll guard, keyboard and XSS-safe lesson blocks OK');
core.go('/app/settings');await until(()=>document.querySelector('[data-logout]'),'Employee profile');
click('[data-theme-toggle]');assert.equal(document.documentElement.dataset.theme,'dark');assert.equal(localStorage.getItem('baros:theme'),'dark');
click('[data-support]');assert.equal(element('.contact-option[href^="mailto:"]').getAttribute('href'),'mailto:ergin.sergey2002@yandex.ru');assert.equal(element('.contact-option[target="_blank"]').getAttribute('href'),'https://t.me/frooppe');click('[data-close]');
click('[data-install]');assert(document.querySelector('.install-steps'));click('[data-close]');
click('[data-logout]');await until(()=>location.pathname==='/'&&document.querySelector('#auth-form'),'Employee logout');
assert.equal((await fetch('/api/me')).status,401);
core.go(invitation.url);await until(()=>document.querySelector('#auth-form [name=organization]'),'Manager invite');
input('#auth-form [name=name]','UI управляющий');submit('#auth-form');
await until(()=>core.state.me?.account?.role==='manager'&&document.querySelector('[data-create]'),'Manager accepted invite');
if(document.querySelector('[data-close]'))click('[data-close]');
core.go('/app/courses');await until(()=>document.querySelector('[data-filter=draft]'),'Manager academy');
click('[data-filter=draft]');assert(!document.querySelector('.course-card'),'Published course hidden by draft filter');
click('[data-filter=published]');assert(document.querySelector('.course-card'),'Published filter retains listeners');
core.go('/app/reports');await until(()=>document.querySelector('#page-content')?.textContent.includes('UI сотрудник'),'Manager sees actual learner report');
core.go('/app/ai');await until(()=>document.querySelector('[data-refresh-jobs]'),'AI history');const before=requests.length;click('[data-refresh-jobs]');assert(element('[data-refresh-jobs]').disabled);assert.match(element('[data-refresh-jobs]').textContent,/Обновляем/);await until(()=>!element('[data-refresh-jobs]').disabled,'Refresh completes');assert(requests.slice(before).some(r=>r.path==='/api/jobs'));assert.match(element('.refresh-status').textContent,/состояние не изменилось/);
console.log('EXPERIENCE: night theme persistence, contact destinations, PWA instructions and actual refresh with visible feedback OK');
core.go('/app/settings');await until(()=>document.querySelector('[data-logout]'),'Manager profile');
click('[data-logout]');await until(()=>location.pathname==='/'&&document.querySelector('#auth-form'),'Manager logout');
assert.equal((await fetch('/api/me')).status,401);
console.log('MANAGER: individual invite, academy filters, employee results, logout OK');
input('#auth-form [name=login]','ui.owner');input('#auth-form [name=password]','audit-owner-password');submit('#auth-form');
await until(()=>core.state.me?.account?.role==='owner'&&document.querySelector('[data-enter-venue]'),'Owner returns');click('[data-enter-venue]');await until(()=>document.querySelector('[data-create]'),'Owner remote dashboard returns');
core.go('/app/ai');await until(()=>document.querySelector('#ai-budget [data-ai-budget-detail=setup]'),'Owner AI instructions');const setupDetails=element('#ai-budget [data-ai-budget-detail=setup]');setupDetails.open=true;click('[data-refresh-jobs]');await until(()=>!element('[data-refresh-jobs]').disabled,'Owner refresh completes');assert.equal(element('#ai-budget [data-ai-budget-detail=setup]'),setupDetails);assert(setupDetails.open,'AI instructions stay open while history refreshes');
console.log('AI: owner instructions remain open and retain focusable DOM while history refreshes OK');
assert(!requests.some(r=>r.status>=500),'No server errors');
console.log('REAL API + DOM AUDIT PASS; requests='+requests.length);
if(core.state.cleanup)core.state.cleanup();
dom.window.close();process.exit(0);
